### ISSUE TITLE
configure: error: pcap.h

### ISSUE THREAD

**Issue by reggi** [ggreer/dsniff#7]
./configure: line 410: test: pcap-bpf.h: integer expression expected
configure: error: pcap.h
./configure: line 299: return: pcap-bpf.h: numeric argument required
./configure: line 309: exit: pcap-bpf.h: numeric argument required

**Comment by ggreer** [comment]
I can't do anything with so little information. Please see [How to Write Good Bug Reports](http://geoff.greer.fm/2015/08/15/how-to-write-good-bug-reports/).
